---
title: "Pertemuan 3 - Conditional Expressions"
author: "ryankny"
date: "2024-09-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### ifelse

```{r}
a = c(26,2,18,9,3)
# a -> 1/a

# if ( a != 0 ){
#   print(1/a)
# } else{
#   print(NA)
# }

# ifelse(param1, param2, param3)
# param1 : kondisi
# param2 : yang dijalankan jika kondisi TRUE
# param3 : yang dijalankan jika kondisi FALSE
ifelse(a != 0, 1/a, NA)
```

### any

```{r}
logical_vector = c(TRUE, TRUE, FALSE)
any(logical_vector)
```
### all

```{r}
logical_vector = c(TRUE, TRUE, TRUE, NA)
all(logical_vector, na.rm = TRUE)
```
```{r}
library(dslabs)
data(murders)

# cek dataset murders yang totalnya < 10
murders$total < 10 # logical_vector
any(murders$total < 10)
all(murders$total < 10)

is.na(murders$total) # logical_vector
any(is.na(murders$total))
```

### fungsi

```{r}
rata2 = function(vector = c(2:26)){
  return(sum(vector)/length(vector))
}

rata2()
rata2(9:18)
```
### for loop

```{r}
compute_s_n = function(n){
  x = 1:n
  return (sum(x))
}

compute_s_n(5)

s = 1:26
s_n = vector(length = length(s))

for(i in s){
  s_n[i] = compute_s_n(i)
}
s_n

```
### sapply

```{r}
sapply(s, compute_s_n)

contoh_list = list(
  a = c(1,7,14,21,28),
  b = c(39,46,53,60,67)
)

# cara manual
sum(contoh_list$a)
sum(contoh_list$b)

# cara singkat
sapply(contoh_list, sum)
```
### mapply

```{r}
luas_persegi_panjang = function(p,l){
  return(p*l)
}

volume_balok = function(p,l,t){
  return(p*l*t)
}

panjang = c(5,12,19,26,33)
lebar = c(6,13,20,27,34)
tinggi = c(4,11,18,25,32)

mapply(luas_persegi_panjang, panjang, lebar)
mapply(volume_balok, panjang, lebar, tinggi)
```


